---
title: "R Notebook"
output: html_notebook
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}
library(readr)
cella <- read_csv("Codice/Metodi_Statistici/lagged_datasets/Cella_15.csv")
plot(seq_along(cella$TemperaturaMandataGlicole)[1:100], cella$TemperaturaMandataGlicole[1:100])
```


```{r}
plot(density(cella$TemperaturaMandataGlicole))
plot(density(cella$TemperaturaRitornoGlicole))
plot(density(cella$TemperaturaCelle))
plot(density(cella$PercentualeAperturaValvolaMiscelatrice))
```

```{r}
plot(cella$TemperaturaMandataGlicoleNominale, cella$TemperaturaMandataGlicole)
```

```{r}
l <- length(cella$TemperaturaMandataGlicole)
ids <- sample(1:l, as.integer(l * 0.2))

train_x <- cella$TemperaturaMandataGlicoleNominale[-ids]
train_y <- cella$TemperaturaMandataGlicole[-ids]

test_x <- as.data.frame(cella$TemperaturaMandataGlicoleNominale[ids])
test_y <- cella$TemperaturaMandataGlicole[ids]

model <- glm(train_y ~ train_x)
summary(model)
```

```{r}
library(Metrics)
preds <- predict(model, newdata = test_x)
mse(test_y, preds)
```
