---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)

cell_file <- "Codice/Metodi_Statistici/lagged_datasets/Cella_15.csv"
cell_number <- 18
target_y <- readRDS("y.rds")

#leggiamo il dataset della cella
cella <- read_csv(cell_file)
cella$Date <- NULL  # rimuove la prima colonna dato che ha l'orario
spec(cella) # per vedere se ci sono problemi
```

```{r}
library(tidyverse)
# fix colonne
cella$PompaGlicoleMarcia <- as.factor(cella$PompaGlicoleMarcia)
cella$Raffreddamento <- as.factor(cella$Raffreddamento)
cella$VentilatoreMarcia <- as.factor(cella$VentilatoreMarcia)

# separa dataset
targets <- cella %>% select(starts_with(paste0(target_y,"F")))
cella <- cella %>% select(-starts_with(paste0(target_y,"F")))


cella$TemperaturaMandataGlicoleNominale <- NULL
# cella$TemperaturaMandataGlicole <- NULL
cella$PompaGlicoleMarcia <- NULL


# cella$VentilatoreMarcia <- NULL

```

Type any R code in the chunk, for example:
```{r}
library(tidyverse)

cella <- as_tibble(cella)
summary(cella) # assicuriamoci che vada tutto# bene
```

```{r}
library(Metrics)

# suddivisione
DATASET_SIZE <- nrow(cella)

TEST_SIZE <- 0.2
# TUNING_SIZE <- 0.8

K_FOLDS <- 10
MAX_K <- 100


id_test <- as.integer(DATASET_SIZE * (1 - TEST_SIZE)):DATASET_SIZE

cella_test <- cella[id_test,]
cella_train <- cella[-id_test,]

dataset_train <- cbind(cella_train, targets[-id_test,4])
dataset_test <- cbind(cella_test, targets[id_test,4])

#                   shuffle
partitions <- split(sample(seq_len(nrow(cella))), cut_number(seq_len(nrow(cella)), K_FOLDS, labels = FALSE))



createDFs <- function(df, partitions, partition_number = 1) {
  # partizione indicata
  valid <- df[unlist(partitions[partition_number]),]
  # tutte le partizioni tranne quella indicata
  tr <- df[-unlist(partitions[partition_number]),]
  return(list(training = tr, validation = valid))
}

compute_metrics <- function(name = "dummy",
                            preds = sample(seq(from = 0, to = 4, by = 0.5), replace = TRUE),
                            test = sample(seq(from = 0, to = 4, by = 0.5), replace = TRUE)) {
  error <- data.frame(name = name,
                      mse = mse(actual = test, predicted = preds), # mean square error
                      rmse = rmse(actual = test, predicted = preds), # root mean square error
                      rmsle = rmsle(actual = test, predicted = preds), # root mean square log error
                      rrse = rrse(actual = test, predicted = preds), # root relative square error
                      rse = rse(actual = test, predicted = preds), # relative square error
                      bias = bias(actual = test, predicted = preds), # bias del modello
                      pbias = percent_bias(actual = test, predicted = preds), # percent bias
                      mae = mae(actual = test, predicted = preds), # Mean Absolute Error
                      rae = rae(actual = test, predicted = preds), # relative absolute error
                      mape = mape(actual = test, predicted = preds), # Mean Absolute Percentage Error
                      mdae = mdae(actual = test, predicted = preds), # Median Absolute Different Error
                      msle = msle(actual = test, predicted = preds), # Mean Squared Log Error
                      smape = smape(actual = test, predicted = preds), #symmetric mean absolute percentage error
                      sse = sse(actual = test, predicted = preds), # sum of the squared differences between two numeric vectors
                      r2 = cor(test, preds)^2
  )

  return(error)
}


errors <- compute_metrics()

DISTANCE <- 2 # distanza di Minkowski
KERNEL <- "optimal" # opzioni: "rectangular", "triangular", "epanechnikov", "biweight", "triweight" , "cos", "inv", "gaussian" and "optimal"

```

# KNN

## Cross Validation
```{r}
library(kknn) # weighted knn

best_ks <- NULL
form <- paste0(target_y,"F60 ~ .")

for(i in 1:K_FOLDS){
  df <- createDFs(dataset_train, partitions = partitions, partition_number = i)
  result <- train.kknn(formula = form, data = df$training, kmax = MAX_K,
                       distance = DISTANCE, kernel = KERNEL
  )
  plot(result)
  best_k <- which.min(result$MEAN.SQU)
  best_ks <- c(best_ks, best_k)

}



```
```{r}
print(best_ks)

best_k <- median(best_ks)
```

```{r}
# test
model <- kknn(formula = form, train = dataset_train, test = dataset_test, k=best_k,
              distance = DISTANCE, kernel = KERNEL)

errors <- rbind(errors, compute_metrics(name=paste0("KNN ( k=",best_k,", Minkowski Distance=",
                                                      DISTANCE,", kernel=", KERNEL,")"),
                                        preds = model$fitted.values, test = dataset_test$TemperaturaRitornoGlicoleF60 ))
```
```{r}
library(ggplot2)

x <- seq_along(model$fitted.values)
df <- data.frame(x,y1=model$fitted.values,y2=dataset_test$TemperaturaRitornoGlicoleF60)

ggplot(df, aes(x)) +                    # basic graphical object
  geom_line(aes(y=y1), colour="black") +  # first layer
  geom_line(aes(y=y2), colour="green") + # second layer
        labs(title = "Temperatura cella", subtitle = "Predetta vs attuale") + xlab("Tempo") +
ylab("Temperatura")
```

```{r}
saveRDS(best_k, file=paste0("Codice/Metodi_Statistici/saved_parameters/KNN/best_k_cella_",cell_number,".rds"))
saveRDS(errors[-1,], file = paste0("Codice/Metodi_Statistici/saved_parameters/metriche_errori/KNN_cella_", cell_number,".rds"))
```

```{r}
# test2

dataset_test <- dataset_test %>% select(-starts_with("TemperaturaRitornoGlicoleP"))
dataset_train <- dataset_train %>% select(-starts_with("TemperaturaRitornoGlicoleP"))
```
```{r}
best_ks <- NULL
form <- paste0(target_y,"F60 ~ .")

for(i in 1:K_FOLDS){
  df <- createDFs(dataset_train, partitions = partitions, partition_number = i)
  result <- train.kknn(formula = form, data = df$training, kmax = MAX_K,
                       distance = DISTANCE, kernel = KERNEL
  )
  plot(result)
  best_k <- which.min(result$MEAN.SQU)
  best_ks <- c(best_ks, best_k)

}

```
```{r}
# test
model <- kknn(formula = form, train = dataset_train, test = dataset_test, k=best_k,
              distance = DISTANCE, kernel = KERNEL)

errors <- rbind(errors, compute_metrics(name=paste0("KNN ( k=",best_k,", Minkowski Distance=",
                                                      DISTANCE,", kernel=", KERNEL,")"),
                                        preds = model$fitted.values, test = dataset_test$TemperaturaRitornoGlicoleF60 ))
```
```{r}
library(ggplot2)

x <- seq_along(model$fitted.values)
df <- data.frame(x,y1=model$fitted.values,y2=dataset_test$TemperaturaRitornoGlicoleF60)

ggplot(df, aes(x)) +                    # basic graphical object
  geom_line(aes(y=y1), colour="black") +  # first layer
  geom_line(aes(y=y2), colour="green") + # second layer
        labs(title = "Temperatura cella", subtitle = "Predetta vs attuale") + xlab("Tempo") +
ylab("Temperatura")
```
